### ISSUE TITLE
http_error  in  gcs_get_object

### ISSUE THREAD

**Issue by alequech** [cloudyr/googleCloudStorageR#106]
Hi, 

I used the googleCompute package to create a VM and now I'm trying to download a 4G .zip file from a bucket like this : 
```r 
readRenviron(".Renviron")
library(googleComputeEngineR)
library(googleAuthR)
library(googleCloudStorageR)

gar_gce_auth()
gcs_get_bucket()
objects <- gcs_list_objects()
gcs_get_object(objects$name[[7]], saveToDisk = "data.zip", overwrite = T)
```
This gives me the following error  

```
Error in UseMethod("http_error") : 
  no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"
Error: Request failed before finding status code: no applicable method for 'http_error' applied to an object of class "c('simpleError', 'error', 'condition')"
```
The image I use to create my vm is [this](https://console.cloud.google.com/gcr/images/dai-jal-2019/GLOBAL/github.com/alequech/docker_spatial?project=dai-jal-2019&organizationId=797212194013&gcrImageListsize=30&login=true)

**Comment by MarkEdmondson1234** [comment]
Can you list objects in the bucket or do any other authenticated storage operations? I wonder if the auth has got mixed up with the compute engine. You should use cloud scopes for best flexibility.


________________________________

**Comment by alequech** [comment]
I get the list of files from my bucket without any problem. I could also send a file to my bucket. 
Reproducing the example of mtcards I sent files to the bucket and I can download them to VM successfully. 

```r
data("mtcars")
gcs_upload(mtcars)
gcs_upload(mtcars, name = "my_mtcars.csv")
gcs_get_object("my_mtcars.csv", saveToDisk = "mtcars.csv", overwrite = T)
```
As to auth I'm using the JSON file I used to create my VM and the .Renviron file. 
```r
GCE_AUTH_FILE="/home/alequech/gcs-key.json"
GCE_DEFAULT_PROJECT_ID="dai-jal-2019"
GCE_DEFAULT_ZONE="us-west1-b"
GCS_SESSION_BUCKET="digeo"
GCS_DEFAULT_BUCKET=digeo
```

**Comment by MarkEdmondson1234** [comment]
Hmm ok, it is the function/object itself then - could you try to run it with `options(googleAuthR.verbose = 1)`  set to get some more logging info?

**Comment by MarkEdmondson1234** [comment]
Hehe, well glad you found the root cause.  Yes disk running out errors are weird to parse out, I had a VM that I couldn't log in to all of a sudden and it turned out the disk was full of logs, that prevented SSH writing to disk with the login key.
