### ISSUE TITLE
Problem with zip::zip in gcs_save_all()

### ISSUE THREAD

**Issue by caewok** [cloudyr/googleCloudStorageR#107]
I am unable to use the `gcs_save_all` function to upload one or more files, because it throws an error with zip:

```
Error in zip_internal(zipfile, files, recurse, compression_level, append = FALSE,  : 
  zip error: `Cannot add file `/home/rstudio/R_Projects/[ProjectFolder]/data/[data_to_upload]` to archive `/tmp/Rtmp0ShoiY/file298718d34075.zip`` in file `zip.c:394`
```

(I changed the bracketed folder names.) 

Tracking this down, it looks like `zip::zip` in `gcs_save_all` does not like full path names. In other words, this fails:

```
directory <- /home/rstudio
files <- file_to_save
zip::zip(tmp, files = file.path(directory, files))

```
But this works:
`zip::zip(tmp, files =  files)`

The solution seems to be to either use `zip::zipr` or `utils::zip` inside `gcs_save_all` instead. But this seems like the sort of bug that should affect others, so perhaps something else is wrong ? I checked the file permissions for both the files to be saved and the tmp folder, and did not see any problems. And `zip::zipr `and `utils::zip` both work without issue. Note also that `zip::zip` is soft-deprecated.

**Comment by MarkEdmondson1234** [comment]
Thanks, looks like as you say I need to update the function.


________________________________

**Comment by MarkEdmondson1234** [comment]
Could you try it now with dev version?  `remotes::install_github("cloudyr/googleCloudStorageR")`

**Comment by caewok** [comment]
Yes, that works. Thanks!
