### ISSUE TITLE
Set GCS_DEFAULT_BUCKET every time it is needed

### ISSUE THREAD

**Issue by byapparov** [cloudyr/googleCloudStorageR#109]
I am getting this error:

```
Bucket is NULL and couldn't find global bucket name.
         Set it via gcs_global_bucket
```

Which could be avoided if env var was checked in the code and bucket was set when it is needed rather than doing it on namespace attachment (which I cannot do several times without error).

**Comment by MarkEdmondson1234** [comment]
Can I see some example code where you see this? It’s avoided mani Ly by specifying the bucket directly via the bucket argument of most of the functions, or setting it at the top of your script using gcs_global_bucket() which puts it in the environment argument for you. Or specify it in .Renviron globally

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by MarkEdmondson1234** [comment]
This is solved using

```r
gcs_global_bucket("blah")
#Set default bucket name to 'blah'
```
