### ISSUE TITLE
API returned: Cannot use ACL API to set object policy when object policies are disabled.

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#111]
Now buckets can be set with [uniform ACL](https://cloud.google.com/storage/docs/uniform-bucket-level-access),  the `gcs_upload` fails as it tries to set them.  Probably solved by having the option to remove that ACL from the request.

**Comment by remibacha** [comment]
Hello Mark,
I still have the message "Error : API returned: Cannot use ACL API to set object policy when object policies are disabled." when using the gcs_upload().
Do you have any update this?
Thank you for your help

**Comment by MarkEdmondson1234** [comment]
At the moment the fix is to not set ACL bucket wide permissions for the bucket, but leave it the old per-object access control.   

I think the fix will be to remove ACL data in the API request for those types of buckets.

**Comment by MarkEdmondson1234** [comment]
From https://cloud.google.com/storage/docs/json_api/v1/objects/insert

> If iamConfiguration.uniformBucketLevelAccess.enabled is set to true, requests that include this parameter fail with a 400 Bad Request response. 

So I think just remove the Acl field, and it will be fixed

**Comment by MarkEdmondson1234** [comment]
I added a potential fix, could you  test it? @remibacha 

Install dev version: `remotes::install_github("cloudyr/googleCloudStorageR")`

**Comment by MarkEdmondson1234** [comment]
```r
gcs_upload(mtcars, bucket = "mark-bucketlevel-acl",
                   predefinedAcl = "bucketLevel")
```

**Comment by remibacha** [comment]
Everything seems OK now! Good job Mark

**Comment by Pit-Storm** [comment]
@MarkEdmondson1234 Thanks for the Hotfix. But i Think you missed the gcs_copy_object() function. There should also be a parametervalue "bucketLevel". I tried it with the latest github commit, but it didn't work. and it says
> Request Status Code:  400
Error: API returned: Invalid string value: 'bucketLevel'. Allowed values: [authenticatedread, bucketownerfullcontrol, bucketownerread, private, projectprivate, publicread]

As long as the update isn't available in CRAN. Can you please post a snippet which removes the ACLs from the call to get this work?

**Comment by MarkEdmondson1234** [comment]
Continued on https://github.com/cloudyr/googleCloudStorageR/issues/132#issuecomment-716453702
