### ISSUE TITLE
Can't auth with email

### ISSUE THREAD

**Issue by vvrably** [cloudyr/googleCloudStorageR#118]
I use R 3.4.4. When I try to authenticate with my email
```
install.packages(c("remotes"))
remotes::install_github("cloudyr/googleCloudStorageR")

library(googleCloudStorageR)
# Check that email is set
Sys.getenv("GARGLE_EMAIL")

gcs_auth()
```
the redirected page show the following error:

400. That’s an error.

Error: invalid_request

Missing required parameter: client_id

How can I fix it?

**Comment by MarkEdmondson1234** [comment]
You need to set up a client id and secret JSON downloaded from your own GCP project. See the website for some details and let me know how it goes.


________________________________
