### ISSUE TITLE
Getting error auto-refreshing stale OAuth token when using a service account.

### ISSUE THREAD

**Issue by Antriksh-Jain-mpf** [cloudyr/googleCloudStorageR#119]
Hi Team,

I am running a job which is taking more that an 60 min and getting exception as "Auto-refreshing stale OAuth token" .

Detail:  I have seen the same issue has been reported on this link: https://github.com/cloudyr/googleCloudStorageR/issues/87 . I have tried to follow the same step given in the solution but it does not work for me. Below is how my docker file looks like :

```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends build-essential r-base r-cran-randomforest python3.7 python3-pip python3-setuptools python3-dev
RUN apt-get install libcurl4-openssl-dev
RUN apt-get install libssl-dev
RUN R -e "install.packages('remotes')"
RUN R -e "remotes::install_github('cloudyr/googleCloudStorageR@v0.5.0')"
RUN Rscript -e "install.packages('clustMixType')"
RUN mkdir scripts
COPY folder/scripts /scripts
COPY folder/resources /resources
ENTRYPOINT ["python3.7", "/scripts/executeFile.py"]
```

so as given in the issue https://github.com/cloudyr/googleCloudStorageR/issues/87, I have downloaded the googleCloudStorageR@v0.5.0 from github .

**Rscript:**

`Sys.setenv("GCS_DEFAULT_BUCKET" = bucket_name, "GCS_AUTH_FILE" = gcs_auth_file)
library(googleCloudStorageR)
gcs_get_object(<loading file from GCS>)`

**<Runs algorithm-  processing is taking more that 60 min>**
The above algorithm  return four files. Try to upload the result file in GCS:

`gcs_upload(file_name1, name = paste0(file_saved_path1, file_name1))
gcs_upload(file_name2, name = paste0(file_saved_path2, file_name2))
gcs_upload(file_name3, name = paste0(file_saved_path3, file_name3))
gcs_upload(file_name4, name = paste0(file_saved_path4, file_name4))`

**Error**:

`Auto-refreshing stale OAuth token.
2020-01-22 13:36:35> Request Status Code: 408
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
There is an issue found in uploading 'size' file to gcs. Please find the error message details below
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
xdg-open: unexpected argument 'minimum-scale=1,'
Try 'xdg-open --help' for more information.`

**Comment by MarkEdmondson1234** [comment]
The error is really odd but I suggest re-authenticating between uploads if you can - are you saying a single upload takes longer than 60 mins?

**Comment by nysthee** [comment]
We got the same issue using auto-authentication (not tested) in combination with Shiny. Not tested on the latest version.

**Comment by Antriksh-Jain-mpf** [comment]
@MarkEdmondson1234 I tried with the re-authenticating between uploads and it works. Thank you.

**Comment by MarkEdmondson1234** [comment]
If using OAuth2 tokens they do have a lifetime of 60 mins, I'm interested if this error occurs if using the JSON service account keys, can't tell from above.
