### ISSUE TITLE
param upload_type in gcs_upload seems to be ignored

### ISSUE THREAD

**Issue by joostvham** [cloudyr/googleCloudStorageR#120]
I'm uploading a RDS file to a bucket:

    > gcs_upload('bla.RDS', 'gs://bucket-name', name='tesarstsst.RDS', upload_type = 'simple')

I've just created the file, its content is unique, its filename is new, the filename on the bucket is also new, and I haven't tried uploading this file before, so literally everything regarding this file is new.

However, still a resumable upload is detected, even though I specifically set the `upload_type` to `'simple'`. 

    2020-05-08 15:33:10 -- File size detected as 7.9 Mb
    2020-05-08 15:33:10 -- Found resumeable upload URL: https://www.googleapis.com/upload/storage/v1/b/bucket-name/o/?uploadType=resumable&name=tesarstsst.RDS&predefinedAcl=private&upload_id=blablablaosomeid
     messages:
    1: No JSON content detected 
    2: In doHttrRequest(req_url, shiny_access_token = shiny_access_token,  :
      API checks failed, returning request without JSON parsing

Any clue where this might be going wrong? Thanks!

**Comment by MarkEdmondson1234** [comment]
Would you mind repeating the call with `options(googleAuthR.verbose = 2)` so I can see more logging information?  It maybe that you don't need to specify the `upload_type`, I usually do not.

**Comment by joostvham** [comment]
I found out why it is ignored, namely this chunk in upload.R

```
UPLOAD_LIMIT <- 5000000L
if (upload_type == "resumable" || file.size(temp) > UPLOAD_LIMIT){
  do_resumable_upload(name = name,
  ...  
} else {
  do_simple_upload(name = name,
  ...
}
```

So whether I'll specify the upload type or not, since the file is 8mb it will automatically try a resumable upload.  

For my purposes, I'm perfectly happy with simple uploads, regardless of the size, and expected the package to respect my upload_type='simple' argument.

Here is a minimal reproducible example to see for yourself:

```
saveRDS(list('bla'='bla'), 'mini.RDS')  # a few kb
saveRDS(list(x=data.frame(x=sample(1:3000000, size=3000000))), 'maxi.RDS')  # 10MB

gcs_upload('mini.RDS', 'gs://bucket-name', name='mini.RDS')
gcs_upload('maxi.RDS', 'gs://bucket-name', name='maxi.RDS')
```

**Comment by MarkEdmondson1234** [comment]
Ah ok, it used to be that they suggested 5MB be the limit for simple uploads but it seems [this guideline has changed](https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload#size), which makes sense if you have a faster connection.  I can change that to be more flexible by parametising the UPLOAD_LIMIT.

It doesn't quite explain though why your upload is failing? It should work for either.

**Comment by joostvham** [comment]
Sorry if I never stated this, but the upload isn't actually failing, that part is working perfectly fine. It's just the warnings that I wanted to get rid off, these 2:

```
1: No JSON content detected 
2: In doHttrRequest(req_url, shiny_access_token = shiny_access_token,  :
  API checks failed, returning request without JSON parsing
```

Which I now realize originate from googleAuthR::gar_api_generator, which calls: googleAuthR::checkGoogleAPIError.

So there is a difference between simple:

  ```
up <-
    gar_api_generator("https://www.googleapis.com/upload/storage/v1",
                      "POST",
                      path_args = list(b = bucket,
                                       o = ""),
                      pars_args = pars_args,
                      customConfig = list(
                        encode = "multipart",
                        httr::add_headers("Content-Type" =  "multipart/related")
                      ))
  
  req <- up(the_body = bb)
  
```

and resumable

```
  up <-
    googleAuthR::gar_api_generator("https://www.googleapis.com/upload/storage/v1",
                                   "POST",
                                   path_args = list(b = bucket,
                                                    o = ""),
                                   pars_args = pars_args,
                                   customConfig = list(
                                     add_headers("X-Upload-Content-Type" = type),
                                     add_headers("X-Upload-Content-Length" = file.size(temp))
                                     
                                   ))
  req <- up(the_body = object_metadata)
```
which causes these warnings.

**Comment by MarkEdmondson1234** [comment]
Ok great, so I'll sort these two issues:

1) Find out why using resumable uploads are generating warnings and fix
2) Let users specify simple over resumable, remove hard limit on when resumable is used

Does that sound good?

**Comment by joostvham** [comment]
That sounds great, thanks for looking into it!

**Comment by BillPetti** [comment]
I'm facing what I think is a similar issue, but in my case the upload is actually failing. I am not asking for it to find a resumable upload, but when I try to upload an updated file it appears to find on and hangs after reading about half of the file, then I get this message:

```
<- HTTP/2 408 
<- content-type: text/html; charset=UTF-8
<- referrer-policy: no-referrer
<- content-length: 1557
<- date: Sat, 16 May 2020 16:10:06 GMT
<- alt-svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<- 
2020-05-16 12:10:06 -- File upload failed, trying to resume...
2020-05-16 12:10:06 -- Retry 3 of 3
Error in gcs_retry_upload(upload_url = upload_url, file = temp, type = type) : 
  Must supply either retry_object or all of upload_url, file and type
Calls: gcs_upload ... do_upload -> do_resumable_upload -> gcs_retry_upload
In addition: Warning messages:
1: No JSON content detected 
2: In doHttrRequest(req_url, shiny_access_token = shiny_access_token,  :
  API checks failed, returning request without JSON parsing
Execution halted
```

And here's my original call:

```
gcs_upload(file = r_object,
           object_function = f,
           upload_type = 'simple',
           name = 'directory/file_name')
```

**Comment by MarkEdmondson1234** [comment]
@BillPetti @joostvham I will track why resumable uploads are failing here https://github.com/cloudyr/googleCloudStorageR/issues/122

For the issue on controlling when an upload is simple or resumable, I have added a new option/function to control the boundary that used to default to 5MB.  Ideally I'd have it as a parameter but that may break existing code.

You can set it before the upload via:

```r
# sets to 10MB
gcs_upload_set_limit(10000000L)

# or use the option directly
option(googleCloudStorageR.upload_limit = 10000000L)
```

Can you see if this works for the github version 0.5.1.9000 ? (`remotes::install_github("cloudyr/googleCloudStorageR")`)

**Comment by joostvham** [comment]
Thanks for adding it! I just tested it, and when setting the upload_limit it now chooses the correct uploading function. 

For me, the uploading worked fine, it's just that the warnings that bothered me.

Thanks for your work developing this package :).

**Comment by MarkEdmondson1234** [comment]
Ok great, thanks for testing - I'm suppressing the warnings for resumable uploads now too as it was because resumable uploads don't return a body response when requesting the upload URL

@BillPetti this doesn't help why your upload is failing, which can be tracked on on #122 - I guess it is unrelated and something to do with the file you are uploading
