### ISSUE TITLE
format_object_size errors when file not found/readable

### ISSUE THREAD

**Issue by stuvet** [cloudyr/googleCloudStorageR#123]
Hi,

I haven't worked out what initially triggered this (likely an issue at my end), but I've seen this error (occasionally) in my logs while uploading a csv:

Error in if (x >= 1024^4) "Tb" else if (x >= 1024^3) "Gb" else if (x >=  : missing value where TRUE/FALSE needed

Reprex:

```
    temp<-'nonExistentFile'  
    file.size(temp)
    # NA
    googleCloudStorageR:::format_object_size(file.size(temp), 'auto')
```
   

I assume there was an issue writing/reading the file at my end, or perhaps a race condition was set up, but it may help others to handle this error gracefully.

Thanks,

Stuart

**Comment by MarkEdmondson1234** [comment]
Thanks Stuart, this is for the messaging feedback on file size, I could put in a check for when that is NA to give a nicer error message ("File had no filesize")
