### ISSUE TITLE
default predefined acl for gcs_upload is not buckets default

### ISSUE THREAD

**Issue by scworland** [cloudyr/googleCloudStorageR#124]
Awesome package! In order to mirror the google storage API, the default predefined acl for an object upload should be the buckets default. From the google storage json api,

"By default, anyone who has OWNER permission or WRITER permission on a bucket can upload objects into that bucket. When you upload an object, you can provide a predefined ACL or not specify an ACL at all. **If you don't specify an ACL, Cloud Storage applies the bucket's default object ACL to the object**. Every bucket has a default object ACL, and this ACL is applied to all objects uploaded to that bucket without a predefined ACL or an ACL specified in the request (JSON API only)"

The default for gcs_upload is private. I can do a pull request for this if it would be helpful.

**Comment by scworland** [comment]
looking through the code in the repo it looks like "bucketLevel" is an option in the current code base but not on cran yet? Also, the current option of "default" is what I had in mind as the default in gcs_upload, so probably don't need a pull request for that. Defaulting to "private" causes issues when collaborating on big teams when everyone is moving stuff in and out of buckets using BQ, python, R, etc and there is fine-grain control

**Comment by MarkEdmondson1234** [comment]
Yes bucketLevel is a recent addition, on CRAN next release. 

Happy to set a new default but need to keep in mind it will error existing code if the ACL doesn’t apply bucket wide, what’s standard now?

**Comment by scworland** [comment]
Thank you for your prompt follow up! What is meant by "what's standard now?". From my understanding, when cloud IAM is used to grant uniform access to a bucket (what google recommends) then I don't think there will ever be issues because the predefined acl parameter doesn't have an effect. The main reason a bucket might have cloud IAM and ACL controls (i.e., fine-grained control) is for interoperability with Amazon S3. I think objects default to 'project-private' which is the same things as passing 'default' using what is currently available on cran, correct?

**Comment by MarkEdmondson1234** [comment]
I was thinking what’s standard for gcloud and gsutil, should probably be prepared here. 

I think they are incompatible defaults though, as if you use bucketLevel on fine grained buckets it will error (which is equivalent to not sending in an ACL metadata) likewise using fine grained api calls (with ACL) errors when used on bucket level access, which triggered the original fix.  I and I guess others have legacy code supporting the former so would need to update, or I can leave it to the user to specify “bucketLevel” each time they upload. I guess a transition period is needed at the very least.

**Comment by scworland** [comment]
googleCloudStorageR currently has an option for "default" which has worked as I would expect. It appears to have the same functionality as "bucketLevel",

```r
  if(!predefinedAcl %in% c("default","bucketLevel")){
    pars_args[["predefinedAcl"]] <- predefinedAcl
  }
```

The default for the google storage API (and the python client 'google cloud storage') is bucket level. When it defaults to 'private' it allows someone to put an object in a bucket that collaborators cannot access. However, it should likely remain as it is if you think it would hinder more workflows then help.
