### ISSUE TITLE
Accessing GCP Storage via Co-lab notebook running R

### ISSUE THREAD

**Issue by ottoman91** [cloudyr/googleCloudStorageR#125]
I am trying to set up a Google Co-lab notebook that runs in R and can read a GCS bucket from a GCP project. I am using the googleCloudStorageR package. To authenticate and read the bucket, the initial Co-lab notebook runs the following Python commands:

!gcloud auth login
!gcloud config set project project_name
!gcloud sql instances describe project_name 

How can I run the above commands in R using the googleCloudStorageR package ? In the documentation for the package, they mention using the gcs_auth function that reads an authentication JSON file. However, since I will be accessing the buckets through a Co-Lab notebook running on R, I do not want to use an authentication file and instead want to authenticate and connect to the GCP storage in real-time from the Co-Lab notebook. Thank you!

**Comment by MarkEdmondson1234** [comment]
Once you have R installed then you can reuse the compute engine login that `gcloud auth login` uses using `googleAuthR::gar_gce_auth()`, then you can use commands like `gcs_list_buckets("project-name")` or set your default bucket via `gcs_global_bucket("my-bucket")`

There is an old example here: https://github.com/MarkEdmondson1234/googleAuthR/blob/master/inst/jupyter/googleAuthR.ipynb let me know if it works ok still.

**Comment by MarkEdmondson1234** [comment]
It seems to be an issue generally with gargle auth that googleCloudStorageR uses - there is a suggested work around there: https://github.com/r-lib/gargle/issues/140

**Comment by ottoman91** [comment]
thanks mark, i will try out your old example and let you know if it works or not. I did try out the suggested workaround, and although I was able to authenticate with google drive on my organization's account, I was still unable to run `gcs` commands, and I got the following error: `No authorization yet in this session!` How do i authenticate googleCloudStorage with this workaround?

**Comment by MarkEdmondson1234** [comment]
If you can generate a token with cloud scopes (or drive) then you should have a token object you can pass to `gar_auth(token=token)` which should put it in the GCS environment for auth.  

If the above isn't working I think I would try using `gcloud` to download your local `googleCloudStorageR` json service key from Google Secret Manager ( https://cloud.google.com/secret-manager ) to a file in the notebook, so its available for the R kernals via normal `gcs_auth("json_file.json")` something like:

!gcloud secrets versions access version-id --secret="secret-id"

!R gcs_auth("auth.json")

Its not ideal as the first auth strategy should work, but you only need to upload to secret manager once and then its available for all future work, I use it a lot now with Cloud Build, Kubernetes etc.

**Comment by ottoman91** [comment]
I tried to generate and save a token by authenticating into google drive via the following code snippet:
```
install.packages("httr")
install.packages("R.utils")
install.packages("googledrive")
if (file.exists("/usr/local/lib/python3.6/dist-packages/google/colab/_ipython.py")) {
  library(R.utils)
  library(httr)
  reassignInPackage("is_interactive", pkgName = "httr", function() return(TRUE))
}
library(googledrive)
options(rlang_interactive = TRUE)
options(gargle_oauth_email = "email_address")
googleAuthR::gar_auth(token =tt)
```
However, I am getting the following error message:
```
Is it OK to cache OAuth access credentials in the folder '/root/.R/gargle/gargle-oauth' between R sessions?

Error: Could not authenticate via any gargle cred function
Traceback:

1. googleAuthR::gar_auth(token = tt)

2. stop("Could not authenticate via any gargle cred function", call. = FALSE)
```
```

**Comment by ottoman91** [comment]
i think when im trying to save the token with `tt <- drive_auth(use_oob = TRUE, cache = FALSE)`, it isnt saved because we have passed `cache = FALSE` . However, according to r-lib/gargle#140, we need to pass `cache = FALSE` for the workaround.

**Comment by MarkEdmondson1234** [comment]
I wouldn't use `drive_auth()` directly as that will save a token with drive scopes, you can use `googleAuthR::gar_auth()` or `gargle::token_fetch()` instead which should generate a token, and you will need cloud scopes e.g. `https://www.googleapis.com/auth/cloud-platform`

I think its ultimately easier using the json key though

**Comment by ottoman91** [comment]
Thanks Mark, it worked! I'm posting the code snippet below for future reference:

```
install.packages("httr")
install.packages("R.utils")
install.packages("googledrive")
install.packages("googleCloudStorageR")
if (file.exists("/usr/local/lib/python3.6/dist-packages/google/colab/_ipython.py")) {
library(R.utils)
library(httr)
reassignInPackage("is_interactive", pkgName = "httr", function() return(TRUE))
}
library(googledrive)
library(googleCloudStorageR)
options(rlang_interactive = TRUE)
options(gargle_oauth_email = “email")
tt <- gargle::token_fetch(scopes = "https://www.googleapis.com/auth/cloud-platform")
googleAuthR::gar_auth(token = tt)
gcs_list_buckets(“project_name")
```

**Comment by ottoman91** [comment]
mark, a weird thing is happening. The Co-lab notebook works fine, but when I make a copy of the notebook and run it again, the `tt` object is NULL, and I am getting the following error message: 
```
Is it OK to cache OAuth access credentials in the folder '/root/.R/gargle/gargle-oauth' between R sessions?

Error: Could not authenticate via any gargle cred function
Traceback:

1. googleAuthR::gar_auth(token = tt)

2. stop("Could not authenticate via any gargle cred function", call. = FALSE)
```

**Comment by MarkEdmondson1234** [comment]
Ok great it worked first time ;) I don't think you then need googledrive for the snippet you posted, its not being used.

When you make a copy I guess the cache folder is then not being copied over - when `gargle::token_fetch()` runs it is placing it in a folder that by default is  '/root/.R/gargle/gargle-oauth' - perhaps in previous runs you were making this cache?

**Comment by ottoman91** [comment]
Thanks @MarkEdmondson1234 for all of your guidance! Here is my final code snippet that works, incorporating all of your feedback:

```
install.packages("httr")
install.packages("R.utils")
install.packages("googledrive")
install.packages("googleCloudStorageR")
if (file.exists("/usr/local/lib/python3.6/dist-packages/google/colab/_ipython.py")) {
  library(R.utils)
  library(httr)
  reassignInPackage("is_interactive", pkgName = "httr", function() return(TRUE))
}
library(googleCloudStorageR) 
options(
  rlang_interactive = TRUE,
  gargle_oauth_email = "email_address",
  gargle_oauth_cache = TRUE
)
tt <- gargle::token_fetch(scopes = "https://www.googleapis.com/auth/cloud-platform")
googleAuthR::gar_auth(token = tt)
```

**Comment by MarkEdmondson1234** [comment]
Ok great! Are you saying you still need to install googledrive for it to work? This will help guide making it easier
