### ISSUE TITLE
Getting 400 Bad Request error when uploading 189MB csv

### ISSUE THREAD

**Issue by samudzi** [cloudyr/googleCloudStorageR#126]
When attempting to upload a somewhat large csv file (180MB), I see in the output that the file gets parsed, but then the upload fails due to HTTP 400 Bad Request error

```<- HTTP/1.1 400 Bad Request
<- X-GUploader-UploadID: AAANsUlp8LenqxJ94mRF-u689lZ0s5JrK3WfCT0Jwd3mNUBW0jIipuwW0I6C0wEjhvNii1lessx35DCqcy4XhVvnZUG9xVfVHA
<- Content-Type: application/json; charset=UTF-8
<- Date: Sat, 25 Jul 2020 08:13:49 GMT
<- Vary: Origin
<- Vary: X-Origin
<- Cache-Control: no-cache, no-store, max-age=0, must-revalidate
<- Expires: Mon, 01 Jan 1990 00:00:00 GMT
<- Pragma: no-cache
<- Content-Length: 500
<- Server: UploadServer
<- Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<- 
2020-07-25 08:13:49 -- File upload failed, trying to resume...
2020-07-25 08:13:49 -- Retry 3 of 3
Error in gcs_retry_upload(upload_url = upload_url, file = temp, type = type) : 
  Must supply either retry_object or all of upload_url, file and type
In addition: Warning messages:
1: No JSON content detected 
2: In doHttrRequest(req_url, shiny_access_token = shiny_access_token,  :
  API checks failed, returning request without JSON parsing
```

I created this script to productionalize my upload process
```uploadCSV <- function(filename="age_complete", df,path="~/ona/data/"){
  setwd(path)
  csv <- paste0(filename,".csv")
  write.csv(df, file = csv)
  payload = paste0(path,csv)
  #browser()
  upload_try <- gcs_upload(bucket="<projectid>",payload)
}
```
output when running `options(googleAuthR.verbose = 2)` includes the contents of the csv file (hundreds of lines long of my csv data, too much to paste here)

When I attempt to re-run after the initial failure, I get 
```2020-07-25 09:30:38 -- File size detected as 189 Mb
2020-07-25 09:30:38 -- Resumable upload
ℹ 2020-07-25 09:30:38 > Token exists.
ℹ 2020-07-25 09:30:38 > Request:  https://www.googleapis.com/upload/storage/v1/b/asoba-241019.appspot.com/o/?uploadType=resumable&name=payload&predefinedAcl=private
Auto-refreshing stale OAuth token.
Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received.
Request failed [ERROR]. Retrying in 1.6 seconds...
Auto-refreshing stale OAuth token.
Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received.
Request failed [ERROR]. Retrying in 3.5 seconds...
Auto-refreshing stale OAuth token.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  gnutls_handshake() failed: An unexpected TLS packet was received.
```

Any thoughts about how I should approach debugging?

I'm able to successfully list my buckets when running `gcs_list_buckets(projectId=projectid)` so I have ruled out an API issue.  Is there an issue with my syntax or arguments that I'm passing in my script?

**Comment by samudzi** [comment]
Sorry, part of the function I used got cut off:

```
uploadCSV <- function(filename="age_complete", df,path="~/ona/data/"){
  setwd(path)
  csv <- paste0(filename,".csv")
  write.csv(df, file = csv)
  payload = paste0(path,csv)
  #browser()
  upload_try <- gcs_upload(bucket="asoba-241019.appspot.com",payload)
}
```

**Comment by MarkEdmondson1234** [comment]
Hmm tough with a large file, I think it may be something to do with encoding and a bad character it can’t accept being uploaded? Or a corrupt bit upload? Can you upload it via other means (like web UI?) - if you can could rule out corrupt file.

But I’ve not seen it before though sorry, I guess it is API end so not much I can change in the code but let me know if I can change anything.

You are triggering the retry upload functions and creating a retry object, are you using that to retry? If it’s a repeatable error I guess it won’t help as it is for bad connections etc.

It may be worth looking at curl’s issues for that error message to see what would trigger it.

________________________________

**Comment by samudzi** [comment]
Yes, the retry URL does get created, but getting curl errors after that.

Is the suggestion here that there is an upper limit to file size?  I've been successful when uploading much smaller files (<10mb).

In terms of corrupt files - these are simply dataframes that I converted to csv using write.csv function.  I'm currently uploading via webUI.  I had previously attempted to send directly to BigQuery via the bigRquery package, but the dataframes were too large.  In general, I'm trying to build an automated data transformation (pull data into dataframe from some API, do some light transformation in R, then send to BigQuery).  Looks like I may have to do orchestration in Python instead :(

**Comment by MarkEdmondson1234** [comment]
There is a 5TB limit so that’s fine. If it works with python then it’s something I can fix, but if you can test to see if the same issue occurs with python that will be helpful, gcloud would be best test.

It’s possible the output of data frame to CSV file corrupts something, can you upload straight from the data.frame object?

I often use R for processing then gcloud for uploads, you can do all that in R using googleCloudRunner and it’s cloud build workflows

________________________________

**Comment by samudzi** [comment]
I just tried uploading as a dataframe
```
gcs_upload(employment_redo)
```

But got the exact same output as before, with the HTTP 400 Bad Request.  

I then tried with the googleapiclient library in Python, and also got an HTTP 400 bad request.  But as I read more, it seems like the google-cloud-storage is actually the better one to use for GCS.

Finally, I tried simple UI upload and that worked.  

I'm still unsure about how to debug the 400 Bad request issue, or why that came up.  Any thoughts there?

**Comment by MarkEdmondson1234** [comment]
Ok that helps or at least points to the file contents rather than the api itself as the issue.  What type of data is it, any free user generated text? Can you report your sessionInfo() to see what encodings are involved.

**Comment by MarkEdmondson1234** [comment]
I note it's an App Engine auto bucket - any settings there that could be preventing uploads? Free account limits etc? Does it still not work with a newly created bucket?

**Comment by samudzi** [comment]
I have a set of functions that generate rbind-ed dataframes from calls using the 'censusapi' R package.  This is an R wrapper for the US Census api.  The strange thing re:encoding is that for smaller dataframes using this function, I was able to send directly to bigquery, so I never tried this package with them.  I used this package for the 189mb csv because the raw dataframe (~500mb) was too big for the bigrquery package.  I figure I would upload to cloud storage and then use gutils to automate the creation of a bigquery table from there.

You're right about encoding, it seems.  Let me check sessioninfo() and get back to you.

**Comment by MarkEdmondson1234** [comment]
What you may want to try to narrow it down is upload each csv separately to GCS and then load them into BigQuery as you go (bigQueryR has some functions to do this as it's a tactic I use a lot) and/or use the GCS compose function which melds lots of data items into one on GCS via gcs_compose_objects() - for that ensure only the first csv has a header.

**Comment by samudzi** [comment]
Sorry for the delay.

I'm still running into issues uploading.  I've tried a number of different dataframes (mostly in the 500mb-1gb) and running into different issues.

Most recently, I tried a 1gb dataframe that was created via simple json download:

`getSocrata = function(json_link,tablename){
  df <- read.socrata(
    "https://data.sfgov.org/resource/wv5m-vpq2.json",
    app_token = Sys.getenv("RSOCRATA_APP_TOKEN"),
    email     = Sys.getenv("RSOCRATA_EMAIL"),
    password  = Sys.getenv("RSOCRATA_PASSWORD")
  )
  assign(tablename,df,envir=.GlobalEnv)
}

When I attempted to upload this one, I got a different error this time:
`Error in strsplit(URL, "") : non-character argument

Here is my sessionInfo()
`> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8    
 [5] LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C             
 [9] LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleCloudStorageR_0.5.1 bigrquery_1.3.1          

loaded via a namespace (and not attached):
 [1] zip_2.0.4         Rcpp_1.0.5        compiler_3.6.3    pillar_1.4.6      googleAuthR_1.3.0 tools_3.6.3      
 [7] digest_0.6.25     bit_4.0.3         jsonlite_1.7.0    memoise_1.1.0     lifecycle_0.2.0   tibble_3.0.3     
[13] gargle_0.5.0      pkgconfig_2.0.3   rlang_0.4.7       DBI_1.1.0         cli_2.0.2         rstudioapi_0.11  
[19] yaml_2.2.1        crul_1.0.0        curl_4.3          xfun_0.16         dplyr_1.0.0       httr_1.4.2       
[25] generics_0.0.2    vctrs_0.3.2       fs_1.4.2          askpass_1.1       tidyselect_1.1.0  bit64_4.0.2      
[31] glue_1.4.1        httpcode_0.3.0    R6_2.4.1          fansi_0.4.1       graphql_1.5       purrr_0.3.4      
[37] magrittr_1.5      ellipsis_0.3.1    assertthat_0.2.1  tinytex_0.25      ghql_0.1.0        openssl_1.4.2    
[43] crayon_1.3.4  `

**Comment by MarkEdmondson1234** [comment]
Ok well sorry you're having troubles but I can't help really without a reproducible example other than moral support :)  The size of the files makes this difficult I realise, you could try it with `gsutil` or `gcloud` instead.  I'd be interested if it works with those and not the library, to pin down if there is something to fix.

**Comment by samudzi** [comment]
Ok, will try with gcloud on command line and let you know

**Comment by samudzi** [comment]
I built the full pipeline (from local environment to GCS to BigQuery) in Python with `gcloud`.  It worked, even with geoJSON files over 1GB.

How can I help further debug this?

**Comment by MarkEdmondson1234** [comment]
Ok good to know, I need a reproducible example to work from

**Comment by samudzi** [comment]
I've been able to resolve this by writing to CSV using fwrite instead of write to csv, and adding upload_type + predefinedAcl arguments
