### ISSUE TITLE
gcs_list_buckets('project-id') - API data failed to parse

### ISSUE THREAD

**Issue by featherduino** [cloudyr/googleCloudStorageR#134]
Error in as.POSIXct.default(t, format = "%Y-%m-%dT%H:%M:%S") : 
  do not know how to convert 't' to class “POSIXct”
Error: API Data failed to parse.  
             Wrote diagnostic object to 'gar_parse_error.rds', use googleAuthR::gar_debug_parsing('gar_parse_error.rds') to 
             debug the data_parse_function.

**Comment by MarkEdmondson1234** [comment]
Thanks, this should be fixed in https://github.com/cloudyr/googleCloudStorageR/issues/100 so if you get the latest version it should be fixed - can you confirm which version you are using?

**Comment by featherduino** [comment]
I am using googleCloudStorageR_0.5.1

**Comment by featherduino** [comment]
Is there anyway i can directly push to BigQuery without cloudStorage bucket ? File size is not that big

**Comment by MarkEdmondson1234** [comment]
Yes, for instance bigQueryR lets you uploaded data.frames directly.
