### ISSUE TITLE
gcs_setup() - No Other option in drop-down menu

### ISSUE THREAD

**Issue by j450h1** [cloudyr/googleCloudStorageR#137]
After running ```gcs_setup()```:

Selection: 2
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Could not find a OAuth 2.0 Client ID via GAR_CLIENT_JSON
Have you downloaded a Client ID file?

1: Yes
2: No

Selection: 2
! You must have a client ID file to proceed.
ℹ Download via https://console.cloud.google.com/apis/credentials/oauthclient :
● **Other** > Name > Create >
● OAuth 2.0 Client IDs >
● Click Download Arrow to the right >
● Download to your computer
  ─────────────────────────────

However, there is no longer an **Other** option in the dropdown menu as per:

![image](https://user-images.githubusercontent.com/7351530/106818364-0b0e9a80-662d-11eb-96ff-541a1e8dd685.png)

Not a big deal, I'm guessing its simply **Desktop app** . Who knows what Google will change it to in a few months...

Great work on this function by the way! **Sidenote**: I often have Owner access to GCP projects, but wondering what could be done to find exact permissions required (or is it not possible at this time?)

**Comment by MarkEdmondson1234** [comment]
Thanks, yeah they keep changing this...found out when doing the video for googleCloudRunner which can apply to here too.

googleAuthR github version just got `gar_service_get_roles()` which will tell you what a service email or your email has access to.  Authenticate with cloud scopes with `gar_auth()` to run it:

```
#gar_service_get_roles(projectId,accountId = NULL,type = c("serviceAccount", "user", "group"))
ga_service_get_roles("project_id", "my_email@you.com", "user")
```

**Comment by j450h1** [comment]
Thanks for clarifying! 

I've tried to give that new function a crack, but opened up a new issue as I've run into a roadblock. But totally see the value once I get things running.

**Comment by MarkEdmondson1234** [comment]
This needs to be fixed on googleAuthR - follow on https://github.com/MarkEdmondson1234/googleAuthR/issues/204
