### ISSUE TITLE
gcs_upload - when uploading dataframe directly includes row number 

### ISSUE THREAD

**Issue by j450h1** [cloudyr/googleCloudStorageR#141]
Would like to have option to remove row numbers of outputted file or make that the default behavior:

```
gcs_upload(events_report, name = glue('path/events_report_{format(DATE, "%Y%m%d")}.csv'))
```

OUTPUT csv file:

```
"","daterangeday"
"1",2017-12-31
"2",2017-12-31
```

Thoughts?

**Comment by j450h1** [comment]
To give some more context, I was trying to upload a dataframe directly to BQ (with only 500 rows) and had mixed results using this function from bigrquery package: ```bq_table_upload``` . However, now I'm currently trying to save to GCS first, which is a success using this ```gcs_upload``` function. However, now I want to take this csv file and load into bq, using below code: ```table <- bq_table(
  project = PROJECT,
  dataset = DATASET
  table = glue('events_report_{format(DATE, "%Y%m%d")}')
)

bq_table_load(
  x = table,
  fields = as_bq_fields(events_report),
  source_uris = glue('gs://{Sys.getenv("GCS_DEFAULT_BUCKET")}/FOLDER/events_report_*.csv'),
  write_disposition = "WRITE_TRUNCATE",
  quiet = FALSE
)``` But of course, the issue is using as_bq_fields, the extra column is not recognized. I've thought of a workaround, but would be nice if there was an easier way to remove the extra row in the first place.

**Comment by MarkEdmondson1234** [comment]
You can do this already as the rows are coming from default behaviour of `write.csv()` - if you supply an `object_function` parameter you can change what function is used to write the R object before it is upload to GCS.

For your example you could supply one without row.names:

```r
## you can supply your own function to transform R objects before upload
f <- function(input, output){
  write.csv(input, file = output, row.names = FALSE)
}

gcs_upload(mtcars, name = "mtcars_csv2.csv", object_function = f)

```

**Comment by j450h1** [comment]
Awesome thanks! That works fine.
