### ISSUE TITLE
Custom class for gcs_get_object() 40x errors

### ISSUE THREAD

**Issue by wlandau** [cloudyr/googleCloudStorageR#153]
When I run `tryCatch(googleCloudStorageR::gcs_get_object(...), error = function(condition_object) browser())`, on an object that does not exist, I find that `condition_object` has class `c("simpleError", "error", "condition")`. Would it be possible to throw a more specific error class for HTML error codes 400-404? For https://github.com/ropensci/targets/pull/722, this would eliminate confusion with other kinds of errors in `targets:::gcp_gcs_head()`.

**Comment by wlandau** [comment]
`rlang::abort(..., class = "http_400")` is a convenient alternative to `stop(...)` for this.

**Comment by MarkEdmondson1234** [comment]
This looks like something that would be best done in `googleAuthR` or `gargle`, but will investigate.

**Comment by MarkEdmondson1234** [comment]
For now its implemented here via 

```r
# https://adv-r.hadley.nz/conditions.html
abort_http <- function(status_code, msg = NULL){
  rlang::abort(paste0("http_",status_code), 
        message = paste(status_code, "error when attempting HTTP -", msg)
  )
}
```

It would be better in googleAuthR though

**Comment by MarkEdmondson1234** [comment]
This was done in `googleAuthR` - thanks for idea.
