### ISSUE TITLE
On Setup: Invalid char in json text

### ISSUE THREAD

**Issue by NerdyBaseballDude** [cloudyr/googleCloudStorageR#154]
Hello. Thank you for making this cool package. Unfortunately, I'm having some issues setting up correctly. I've watched the video and followed the tutorial, but I'm still running into an issue. Whenever I go through the `cr_setup()` I go through the prompts just  fine until I hit the prompt to create a service key. I get redirected to google where I approve the account, but whenever I return to R, I have this error waiting for me:

```
Selection: 2
i Creating service key file - choose service account name (Push enter for default 'googlecloudrunner')
service account name: R With Google Sheets
i Creating service account R With Google Sheets
√ Setting client.id from C:/MizzouInGameService/GoogleCloudCreds.json
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
i 2022-01-07 17:31:27 > Request Status Code:  400
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
Error in value[[3L]](cond) : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
```

I tried going through the console and creating a service account manually, and then adding the key to the .Renviron file. I pass the setup correctly, but whenever I go to do any of the cr_setup_test requirements, they all fail with the same error. Any ideas?

**Comment by MarkEdmondson1234** [comment]
Could you try with latest GitHub version installed? the was an update to the APIs that may have caused this with CRAN version.

**Comment by NerdyBaseballDude** [comment]
Thank you for the quick response. I made some progress but am still running into issue. I installed from Git, then ran setup again. I was able to create a service account as expected, but whenever I tried to set up a bucket on the next prompt, I got this error message again:
```
Selection: 1
Do you want to make a new Cloud Storage bucket?

1: Not now
2: Absolutely not
3: Absolutely

Selection: 3
What name will the bucket be? It will be created in your project:  R With Google Sheets : new-bucket
Request failed [503]. Retrying in 1 seconds...
Request failed [503]. Retrying in 3.6 seconds...
i 2022-01-08 08:52:20 > Request Status Code:  503
i 2022-01-08 08:52:20 > Trying again:  1  of  5
i 2022-01-08 08:52:23 > Trying again:  2  of  5
i 2022-01-08 08:52:27 > Trying again:  3  of  5
i 2022-01-08 08:52:36 > Trying again:  4  of  5
i 2022-01-08 08:52:52 > Trying again:  5  of  5
i 2022-01-08 08:53:25 > All attempts failed.
Error: API returned: We encountered an internal error. Please try again.
```

I then tried to configure the bucket manually in Google Cloud, but then got this error:
```Selection: 2
Do you have an existing Cloud Storage bucket you want to use?

1: No way
2: I agree
3: Absolutely not

Selection: 2
i Fetching your buckets under the project-id:  R With Google Sheets
Request failed [503]. Retrying in 2 seconds...
Request failed [503]. Retrying in 1.7 seconds...
i 2022-01-08 08:55:24 > Request Status Code:  503
i 2022-01-08 08:55:24 > Trying again:  1  of  5
i 2022-01-08 08:55:26 > Trying again:  2  of  5
i 2022-01-08 08:55:31 > Trying again:  3  of  5
i 2022-01-08 08:55:39 > Trying again:  4  of  5
i 2022-01-08 08:55:56 > Trying again:  5  of  5
i 2022-01-08 08:56:29 > All attempts failed.
x Could not fetch a list of your buckets - API returned: We encountered an internal error. Please try again.
NULL
What is the name of your bucket? e.g. my-bucket-name: r-with-sheets-bucket
i Validated Cloud Storage bucket
* Configuring your .Renviron...
GCS_DEFAULT_BUCKET=r-with-sheets-bucket
i Writing to C:/Users/MadisonDC/Documents/.Renviron
√ Added GCS_DEFAULT_BUCKET=r-with-sheets-bucket to .Renviron and set via Sys.setenv()```

It looks like it worked, but it's still failing the checks.

**Comment by NerdyBaseballDude** [comment]
Ok, I was able to get through the setup correctly (I believe), but whenever I go to test, I'm getting credential errors in the build. This is the output for the first docker build:
```
Step #0: runtime.goexit()
Step #0: 	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000038fe8 sp=0xc000038fe0 pc=0x46b861
Step #0: error pushing image: resolving pushAuth: error getting credentials - err: exit status 2, out: ``
Finished Step #1
ERROR
ERROR: build step 1 "gcr.io/kaniko-project/executor:latest" failed: step exited with non-zero status: 1
Finished Step #0
```
Any thoughts on this? I double checked that the paths are correct in the .Renviron file.

**Comment by MarkEdmondson1234** [comment]
I think you have now got through your setup but am running into a bug with kaniko cache - it should be fixed in GitHub version of googleCloudRunner though? Can you show sessionInfo() to check your versions.

**Comment by MarkEdmondson1234** [comment]
Oh I see it in previous post - yes it's the CRAN version - please install GitHub version.

**Comment by NerdyBaseballDude** [comment]
Sorry, I think I'm having some issues installing the GitHub version. I first uninstalled the CRAN version and then tried to install the GitHub version this way:
```
> remotes::install_github("MarkEdmondson1234/googleCloudRunner")
Downloading GitHub repo MarkEdmondson1234/googleCloudRunner@HEAD
Downloading GitHub repo andodet/googlePubsubR@HEAD
√  checking for file 'C:\Users\MadisonDC\AppData\Local\Temp\Rtmp8UIfyb\remotes23e04004260f\andodet-googlePubsubR-d14dda8/DESCRIPTION' ... 
-  preparing 'googlePubsubR':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'googlePubsubR_0.0.2.tar.gz'
   
Downloading GitHub repo andodet/googlePubsubR@HEAD
Skipping googlePubsubR, it is already being installed
√  checking for file 'C:\Users\MadisonDC\AppData\Local\Temp\Rtmp8UIfyb\remotes23e0113f4300\MarkEdmondson1234-googleCloudRunner-4905ead/DESCRIPTION' ...
-  preparing 'googleCloudRunner': (5s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (848ms)
-  checking for empty or unneeded directories
-  building 'googleCloudRunner_0.4.1.9001.tar.gz'
   
> library(googleCloudRunner)
Error in library(googleCloudRunner) : 
  there is no package called ‘googleCloudRunner’
```
However, as you can see, something failed. I restarted and tried to load the package in again, but R still didn't recognize it. What am I doing wrong here?

Thank you so much for your patience and help by the way. It is very much appreciated.

**Comment by MarkEdmondson1234** [comment]
You unfortunately seem to be running into several issues at once which is never nice when you are getting to know a system :)

1. Install via `remotes::install_github("MarkEdmondson1234/googleCloudRunner")` as you show you did, but I don't know why its not working.  Perhaps an issue on https://github.com/r-lib/remotes/ will help track that down
2. Once installed you should see version ending with .9000 when you use `sessionInfo()`.  I see you want googleCloudRunner, but googleCloudStorageR and googleAuthR involved that may need installing from github too, which is usually much easier!
3. The original issue was an API update that broke the CRAN version you were using, but you shoudl also be able to set up via the GCP setup guide on the website regarding service keys etc., althugh of course this is complicated if not done before which is why the function exists in the first place.

**Comment by NerdyBaseballDude** [comment]
Even though whenever I did ``` cr_setup_test() ``` it showed that the setup failed, I was able to deploy and use your package successfully. I'm not sure why deploying my own stuff worked whenever the test didn't, but regardless, I want to thank you first for your super awesome package, and second of all for your kind, fast, and concise responses to my questions. You are awesome!!!

**Comment by MarkEdmondson1234** [comment]
Glad it got sorted!
