### ISSUE TITLE
Can gcs_upload_set_limit be set above R's integer limit?

### ISSUE THREAD

**Issue by JamieCranston** [cloudyr/googleCloudStorageR#160]
Apologies If I'm missing something quite new to GCP as a platform. 

I've been hitting issues uploading large files to buckets using gcs_upload. The documentation says that it should work for up to 5 Terabytes which I think is the google limit.

The default for  gcs_upload_set_limit  is 5Mb. 

The function asserts that the input must be an integer but integers in R are capped at about 2 billion, i.e 2 Gigabytes. 

I change this manually options(googleCloudStorageR.upload_limit = upload_limit) to a higher value and it works with my large upload.

Is there a reason to restrict this to integer values? I'm not sure if I'm going about this the wrong way.

**Comment by MarkEdmondson1234** [comment]
It's probably me overlooking something, could I see an example?

**Comment by MarkEdmondson1234** [comment]
The default is mostly there for users on slow connections, it swaps to a different method of upload (resizable) when over that limit.

**Comment by JamieCranston** [comment]
So I ran a function like this, running it the first time didn't work with an around 1Gb file. 
```
if (file_type == ".RData") {
        original_name <- deparse(substitute(object))
        assign(original_name, object)
        googleCloudStorageR::gcs_save(list = original_name, file = paste0(folder_name, 
            filename, suffix_to_file_name, file_type), bucket = bucket)
    }
```
It had this error, which I think is caused by the size of the object?

![image](https://user-images.githubusercontent.com/36704853/170034868-fa8c3427-fb46-4653-9756-30b8e6b73391.png)

As I reran using a higher limit and it worked.
```
googleCloudStorageR::gcs_upload_set_limit(2000000000L)
```
However, this fails as the integer is too large.
```
googleCloudStorageR::gcs_upload_set_limit(50000000000L)
```
I adjusted this option as follows which is what happens after the assertthat in the gcs_upload_set_limit function and it worked for an even larger file.
```
options(googleCloudStorageR.upload_limit = 50000000000)
```

**Comment by MarkEdmondson1234** [comment]
Ok, maybe I need to fix the resumable method of uploading, which kicks in when your object is above the threshold, but the simple version worked for you as I guess you are on a fairly good connection.  

The integer thing is me overlooking it had a limit in R, but if it works ok with your alternative alls good.

**Comment by MarkEdmondson1234** [comment]
To fix this should I just remove the integer limit to the option? e.g `options(googleCloudStorageR.upload_limit = 50000000000)` and not `options(googleCloudStorageR.upload_limit = 50000000000L`)

**Comment by JamieCranston** [comment]
I think so, changing the assert_that call in gcs_upload_set_limit to is.number?
```
gcs_upload_set_limit <- function (upload_limit = 5000000) 
{
    assert_that(is.scalar(upload_limit)) # Remove is.integer(upload_limit) assertion / replace with is.number
    myMessage("Setting upload limit for simple uploads to ", 
        upload_limit)
    options(googleCloudStorageR.upload_limit = upload_limit)
}
```
