### ISSUE TITLE
gcs_upload(): not possible to upload to a folder inside a bucket

### ISSUE THREAD

**Issue by lisovyk** [cloudyr/googleCloudStorageR#166]
The title says it all – I can write an object to the bucket with
```
gcs_upload(datapath, bucket = 'bucket-name', name = name)
```

But not possible to write to a folder inside a bucket:
```
Browse[1]>         gcs_upload(datapath,bucket = 'bucket-name/folder-name', name = name)
ℹ 2022-09-21 12:12:28 > File size detected as  126.7 Kb
ℹ 2022-09-21 12:12:28 > Request Status Code:  404
Error in value[[3L]](cond) : http_404 Unspecified error
```

If there is something obvious I am missing, please let me know!

**Comment by lisovyk** [comment]
Never mind my inattentive self, it is possible with 
`gcs_upload(datapath,bucket = 'bucket-name/folder-name', name = sprintf('folder-name/%s', name)`!

**Comment by MarkEdmondson1234** [comment]
Yep, bucket is only the stem, the folder is in reality a name with a / in it :)
