### ISSUE TITLE
Fail test for gcs_load

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#29]
I can't get this to work, but when I run the code inside the `test_that` function it works ok.

I think its something to do with where the `load()` puts the objects but passing in various environments doesn't work either..  @leeper any clues?

```r
## I can't get this test to work...but it works fine locally
test_that("We can reload the R session", {

  a <- 1
  b <- "test"
  saved <- gcs_save(file = ".RData")
  expect_true(saved)
  rm(a,b)

  loaded <- gcs_load(file = ".RData")
  expect_true(loaded)
  a <- get("a")
  b <- get("b")
  expect_true(a == 1)
  expect_true(b == "test")
})
Error: Test failed: 'We can reload the R session'
* object 'a' not found
1: get("a") at :11

## but this works fine
  a <- 1
  b <- "test"
  saved <- gcs_save(file = ".RData")
  expect_true(saved)
  rm(a,b)

  loaded <- gcs_load(file = ".RData")
  expect_true(loaded)
  a <- get("a")
  b <- get("b")
  expect_true(a == 1)
  expect_true(b == "test")
```

**Comment by leeper** [comment]
I believe testthat expressions are evaluated inside some kind of environment, so presumably `get()` isn't seeing the objects as they're being loaded into the .GlobalEnv. Perhaps create a new environment, use that  in your `gcs_load()` call and then look for the objects there?

Also, small note, the `aws.s3::s3save()` function saves specific objects (using `save()`) not the whole environment. I should add an equivalent to what you've done here with something like `s3save_image()` but it might makes sense to have `gcs_save()` work like `save()` and `gcs_save_image()` do the whole workspace?

**Comment by MarkEdmondson1234** [comment]
I tried to explictly include the environment, but still no joy:

```r
## I can't get this test to work...but it works fine locally
test_that("We can reload the R session", {

  a <- 1
  b <- "test"
  saved <- gcs_save_image(file = ".RData")
  expect_true(saved)
  rm(a,b)

  ee <- environment()

  loaded <- gcs_load(file = ".RData", envir = ee)
  expect_true(loaded)
  a <- get("a", envir = ee)
  b <- get("b", envir = ee)
  expect_true(a == 1)
  expect_true(b == "test")
})
Error: Test failed: 'We can reload the R session'
* object 'a' not found
1: get("a", envir = ee) at :13
```
...but this works:
```r
 a <- 1
  b <- "test"
  saved <- gcs_save_image(file = ".RData")
  expect_true(saved)
  rm(a,b)

  ee <- environment()

  loaded <- gcs_load(file = ".RData", envir = ee)
  expect_true(loaded)
  a <- get("a", envir = ee)
  b <- get("b", envir = ee)
  expect_true(a == 1)
  expect_true(b == "test")
```

```

**Comment by MarkEdmondson1234** [comment]
..and I changed it to `gcs_save_image` and `gcs_save`, with the same problem with the test but ok when I try it manually.

**Comment by leeper** [comment]
Got it here: https://github.com/cloudyr/googleCloudStorageR/blob/fde3e1425346e3f912e70b6f46c103eeb1ecf524/R/rsession.R#L95 you're calling `load(file)` where file is the formal argument, not the response from `gcs_get_object()`.

Also, you hard coded `envir` here: https://github.com/cloudyr/googleCloudStorageR/blob/fde3e1425346e3f912e70b6f46c103eeb1ecf524/R/rsession.R#L62

**Comment by MarkEdmondson1234** [comment]
Woop, all tests pass now, thanks for the help!  I put in an option so you could pass in the environment to save.image, and passed that to gcs_save().  Hopefully this prevented a bug down the line :)

**Comment by leeper** [comment]
:+1:

**Comment by MarkEdmondson1234** [comment]
Ok, I have to now ask how to get these to run on Travis?  All it needs to do is load the environment variable `GCS_AUTH_FILE` which specifies the path, then run the encrypted auth.json.enc file, but I've tried about 10 different variations and it doesn't work.  

I keep getting a `iv undefined` error https://travis-ci.org/cloudyr/googleCloudStorageR

**Comment by leeper** [comment]
I find it's easiest to just set these as environment variables [using the `travis` command line tool](https://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key), rather than trying to manually decrypt.

**Comment by MarkEdmondson1234** [comment]
Ok cool, the ENV is there, but its the main problem that the script it adds to the travis, errors:

``openssl aes-256-cbc -K $encrypted_98ede7773294_key -iv $encrypted_98ede7773294_iv -in auth.json.enc -out auth.json -dopenssl aes-256-cbc -K $encrypted_98ede7773294_key -iv $encrypted_98ede7773294_iv -in auth.json.enc -out auth.json -d``

I try it in the package folder and get the same.  Google-wu letting me down, may try SO :)

**Comment by MarkEdmondson1234** [comment]
Seems like it needs to be on the main branch for the encryption to work.  nice to know... :)

**Comment by leeper** [comment]
Yea, I think that's a security measure.

**Comment by MarkEdmondson1234** [comment]
I think I'm almost there, I just need to know how to specify the file location so the auth function on travis can find it? `auth.json`, `/home/travis/auth.json`, `/home/travis/cloudyr/googlecloudStorageR/auth.json` donøt work so far ;)

**Comment by MarkEdmondson1234** [comment]
w00p, all checks passed now.
