### ISSUE TITLE
drat.sh needed?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#49]
Hi @leeper 

I see this line in my travis file:

```
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  drat.sh
```

..but I don't have `drat.sh` in my repo - is this as intended?

**Comment by leeper** [comment]
Yes, you should have a `drat.sh` file. It's what pushes the built package into [the cloudyr drat repository](http://cloudyr.github.io/drat/).

Just pull the copy from here: https://github.com/cloudyr/pkgtemplate/blob/master/drat.sh (no need to change anything in it).

**Comment by MarkEdmondson1234** [comment]
Cool, done
