### ISSUE TITLE
Demo listing buckets in a project doesn't work

### ISSUE THREAD

**Issue by jarodmeng** [cloudyr/googleCloudStorageR#5]
I tried the demo example to list buckets I have in my project, but was met with an API error.

```r
library(googleCloudStorageR)
options(googleAuthR.scopes.selected =
  "https://www.googleapis.com/auth/devstorage.full_control")
googleAuthR::gar_auth()

proj <- "my project"

buckets <- gcs_list_buckets(proj)
```

The error says: 
> JSON fetch error: Access Not Configured. Cloud Storage JSON API has not been used in project 201908948134 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/storage_api/overview?project=201908948134 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

It seems that `201908948134` refers to the default OAuth client in `googleAuthR`. Is it possible that the default client doesn't have Cloud Storage JSON API enabled and it's causing the error?

**Comment by MarkEdmondson1234** [comment]
Yes it's not enabled GCS carries a charge and Intealised I didn't want people to be able to charge my credit card :). I need to update the docs to say that though - it's should work once you use your own Google project keys and add a credit card to it. There is a guide to that in the googleAuthR readme that I will migrate to hear soon. Let me know how it goes.

**Comment by MarkEdmondson1234** [comment]
I have update the readme with the necessary information: https://github.com/cloudyr/googleCloudStorageR

**Comment by MarkEdmondson1234** [comment]
Ok cool, I've turned it back on then :)

**Comment by jarodmeng** [comment]
Confirmed it works now. Thanks.
