### ISSUE TITLE
gcs_load objects from "subdirectories" within buckets

### ISSUE THREAD

**Issue by tomsing1** [cloudyr/googleCloudStorageR#52]
The `gcs_save` function accepts a directory-like path to a cloud location, e.g.

`gcs_save(object, file = "my_bucket/my_dir/object.RData")
`

but the `gcs_load` function fails with the same parameter, because it uses the full 'file' parameter as the name for the path to save the local file. 

For example, in the case above, it would download the `object.RData` file and try to save it as `my_bucket/my_dir/object.RData` in the current working directory. If `my_bucket/my_dir/` doesn't exist, the following error is returned (after the transfer):

```
Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
  cannot open file 'my_bucket/my_dir/object.RData': No such file or directory
```

It seems the `saveToDisk` parameter might need to be exposed in `gcs_load` (and perhaps set to the `tempdir()`as default)?

Or perhaps the downloaded file could be loaded directly e.g. with

`load(rawConnection(gcs_get_object( "my_bucket/my_dir/object.RData")))
`

**Comment by MarkEdmondson1234** [comment]
Hmm yes, I should either update the documentation to say "no folders" or have a work around for this. 

You should be able to load the object directly using gcs_get_object() which handles the folders ok (which as you indicate don't really exisit, more like filenames with / in them) 

Thanks for the report though, I will look at this and use this as the test case as its obviously expected behaviour - could it perhaps create the folder for you if it doesn't exist?

**Comment by tomsing1** [comment]
Thanks for quick response! Yes, your suggested `gcs_get_object` alternative works nicely. I like it better than creating the whole directory tree, because it loads the object into the R session without messing up my working directory.

**Comment by MarkEdmondson1234** [comment]
When I'm saving objects I tend to use `gcs_upload()` and `gcs_get_object()` and my original intention was `gcs_save()` and `gcs_load()` was only for R images, but it seems a bit unclear which to use at the moment I think.

**Comment by tomsing1** [comment]
Oh, I see. I understand now. To me the `gcs_save` and `gcs_load` function names seemed to indicate that they would be replacements for the `save` and `load` commands, respectively. Perhaps loading and saving R images could be considered a special use case for a the generally useful functionality?

**Comment by MarkEdmondson1234** [comment]
I think as you say exposing the `saveToDisk` argument is the solution, thats easy enough.  

The main difference between `gcs_save()` and `gcs_upload()` is you can pass multiple objects in like you can with `save` to `gcs_save`, and it puts them all in one RData file

**Comment by MarkEdmondson1234** [comment]
@tomsing1 sorry I only just got around to do this, but the saveToDisk is in now.
