### ISSUE TITLE
Possibility of generating signed URLs for objects

### ISSUE THREAD

**Issue by seandavi** [cloudyr/googleCloudStorageR#54]
A little out-of-scope, but would be useful to be able to do this.

https://cloud.google.com/storage/docs/access-control/signed-urls

**Comment by MarkEdmondson1234** [comment]
Have you tried the access control functions to give people access? I use those so people can download files behind a Google login. What do signed URLs give different from those?

**Comment by MarkEdmondson1234** [comment]
Ok, its for users without a Google account for temp access.  I did try to add this before but I could never get the signed URL key correct :)  But I will take another look.

**Comment by seandavi** [comment]
@deflaux, @jbingham, or @googlegenomics, is generating a cloud storage signed URL something that you have done successfully in R?

**Comment by seandavi** [comment]
And for my own notes:

- https://github.com/GoogleCloudPlatformBook/code-snippets/blob/master/cloud-storage/signed-urls.py
- https://cran.r-project.org/web/packages/openssl/openssl.pdf (might be applicable)?

**Comment by jbingham** [comment]
Not me. Anyone else?

**Comment by deflaux** [comment]
Same here - have not tried it.  As an alternative, from R one could call out to [gsutil signurl](https://cloud.google.com/storage/docs/gsutil/commands/signurl).

**Comment by seandavi** [comment]
Thanis @deflaux and @jbingham.  @MarkEdmondson1234, I'll see if I can find some time to look into this, but it may be a while before I get to it.  This would probably be a good question for Stackoverflow--want to ask?

**Comment by seandavi** [comment]
I went ahead and asked.  Not well-written, but....

http://stackoverflow.com/questions/40747470/signing-google-cloud-storage-url-in-r

**Comment by MarkEdmondson1234** [comment]
I got as far as trying openssl for the encryption, which is preferred because it is already a dependency https://cran.r-project.org/web/packages/openssl/vignettes/crypto_hashing.html

I'd prefer not to call out to gsutil/gcloud if possible, the rest of the functionaility is done directly via the JSON API and it would be a shame to add an external dependcy just for this functionality.  Also the system calls necessary don't play nicely with RStudio sometimes, causing a crash.

**Comment by seandavi** [comment]
@MarkEdmondson1234, I think the openssl crypto package is where the money is. We just need to sort out the [very tedious] details.

**Comment by seandavi** [comment]
Just some more notes....

This is getting closer:

```r
curl::curl_escape(base64_encode(openssl::signature_create(data=charToRaw('abc'),key=readLines('~/.ssh/id_rsa'))))
```

**Comment by seandavi** [comment]
This is the right combination. Still needs some work with regard to headers, but this works to generate the `Signature` piece of a signed url.

```r
string = "GET\n\n\n1489111754\n/isb-cgc-04-0020-reference-data/gencode.v24.transcript2gene.tsv"
Signature = curl::curl_escape(base64_encode(signature_create(data=charToRaw(string),key=x$private_key,hash=sha256)))
```

I'll work on a pull request when I get a little more free time.

**Comment by MarkEdmondson1234** [comment]
@seandavi how is this looking?  I'm thinking about a new CRAN release soon so wondering if this could be part of it. No worries if you haven't time.

**Comment by MarkEdmondson1234** [comment]
I gave it a go, with this code https://github.com/cloudyr/googleCloudStorageR/commit/007b14f3294896b0e541fd2742fb622d2ff177da - but not working yet.

**Comment by MarkEdmondson1234** [comment]
Woop, all working now:

```r
obj <- gcs_get_object("LICENSE", meta = TRUE)
signed <- gcs_signed_url(obj)

 temp <- tempfile()
  on.exit(unlink(temp))

  download.file(signed, destfile = temp)
```
