### ISSUE TITLE
gcs_object_metadata requires name

### ISSUE THREAD

**Issue by seandavi** [cloudyr/googleCloudStorageR#56]
It looks like gcs_metadata_object() requires object_name.  It would be nice if the name could be specified in only one place during upload when specifying metadata.

**Comment by MarkEdmondson1234** [comment]
Could you give an example of how it would look? Shouldn't be too bad to add.

**Comment by seandavi** [comment]
I kind of thought that the `gcs_metadata_object()` shouldn't be dealing with names at all, so perhaps simply removing the `object_name` from `gcs_metadata_object()` would do it?  That allows the same metadata object to be used more than once and also removes ambiguity about where the name comes from when using gcs_upload.

**Comment by MarkEdmondson1234** [comment]
@seandavi I just set the default to NULL which should mean its not required, let me know if it tests out

**Comment by seandavi** [comment]
works for me.  Thanks!
