### ISSUE TITLE
Possibility of having gcs_get_object simply taking a full gs:// URI?

### ISSUE THREAD

**Issue by seandavi** [cloudyr/googleCloudStorageR#57]
I often find myself with objects using the fully-qualified URI including `gs://BUCKETNAME/....`.  While I know that this would change the current API, what do you think about having `gcs_get_object` either "do the right thing" with those types of URIs or even making that the default behavior.  Just wanted to hear your thoughts.

**Comment by MarkEdmondson1234** [comment]
That was easy enough to add in, I used this helper function:

```r
# Parse gs:// URIs to bucket and name
gcs_parse_gsurls <- function(gsurl){
  testthat::expect_type(gsurl, "character")

  if(grepl("^gs://", gsurl)){
    ## parse out bucket and object name
    bucket <- gsub("^gs://(.+?)/(.+)$","\\1", gsurl)
    obj <- gsub(paste0("^gs://",bucket,"/"), "", gsurl)

    out <- list(bucket = bucket, obj = obj)
  } else {
    # not a gs:// URL
    out <- NULL
  }

  out

}
```

Test it out, and if looks ok it can be in the next CRAN release.

**Comment by seandavi** [comment]
Quick testing--looks great.  Thanks again for your generosity.
