### ISSUE TITLE
Gettting publicRead URL from gcs_upload

### ISSUE THREAD

**Issue by mwhitaker** [cloudyr/googleCloudStorageR#59]
Hi Mark,

Thanks for a great package. This is not really an issue, but was wondering about the public URL when you use `gcs_upload(file, predefinedAcl = "publicRead")`. 

    ==Google Cloud Storage Object==
    .
    .
    Download URL:    https://storage.cloud.google.com/bucket/file.png

However, the file would be publicly accessible at something like https://storage.googleapis.com/bucket/file.png not https://storage.cloud.google.com/bucket/file.png

Obviously I can just build the URL myself but was curious if the "right" URL is somewhere in the response, just in case Google changes URLs at some point.

**Comment by mwhitaker** [comment]
Actually I think it's just standard practice to build the URL yourself for public as detailed here https://cloud.google.com/storage/docs/access-public-data and I guess that URL ain't going to change.

    1. Get the name of the bucket containing the public data.
    2. Use the following URI to access an object in the bucket:

        http://storage.googleapis.com/[BUCKET_NAME]/[OBJECT_NAME]

Just answering my own question then ;-) . Feel free to close this one!

**Comment by MarkEdmondson1234** [comment]
Hi @mwhitaker - there is a convenience function for generating the download URL, I presumed for all predefinedAcls: `gcs_download_url()`

```r
> gcs_download_url("blah.csv")
[1] "https://storage.cloud.google.com/mark-edmondson-public-files/blah.csv"
```

The print method uses this - that seems to work in my tests but is that not always the case?

**Comment by mwhitaker** [comment]
Right, but that URL https://storage.cloud.google.com/mark-edmondson-public-files/blah.csv would not be accessible to unauthenticated users in a browser.

For example, this works https://storage.googleapis.com/analyticsbuddyio/ya.png but this doesn't https://storage.cloud.google.com/analyticsbuddyio/ya.png. My use case is to knit a Rmd document that is not self_contained.

**Comment by MarkEdmondson1234** [comment]
Ah ok. I will look to update that.

**Comment by MarkEdmondson1234** [comment]
The public URL isn't in the API response but I added it to the print method.
