### ISSUE TITLE
Error (lexical error: invalid char in json text) when uploading a dataframe from a Compute Engine VM

### ISSUE THREAD

**Issue by prcbnt** [cloudyr/googleCloudStorageR#60]
Hello,

Thank you for the amazing work on the package !

I am trying to `gcs_upload` dataframes from a Compute Engine VM into a Cloud Storage bucket (obviously), and I constantly get the following error 
```
Request Status Code: 400
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
```

Here is the code I used to test the function with a very simple dataframe

```
library(googleCloudStorageR)
gcs_auth()
proj <- "XXXXX"
buckets <- gcs_list_buckets(proj)
bucket <- gcs_get_bucket(buckets[[1]])

employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))

employ.data <- data.frame(employee, salary, startdate)

gcs_upload(employ.data, bucket = bucket)
```

Auth works fine and I can't seem to find the solution. Any idea of what might be the problem ?

Thanks !

**Comment by MarkEdmondson1234** [comment]
Hi @prcbnt thanks for trying the package:

Perhaps it is the wrong bucket type specified?  I set my buckets via the environment files like this:

```
GCS_DEFAULT_BUCKET="bucket-name"
GCS_AUTH_FILE="/Users/mark/auth.json"
```

Then when I run the below code it works for me:

```r
> library(googleCloudStorageR)
Setting scopes to https://www.googleapis.com/auth/devstorage.full_control
If you need additional scopes set do so via options(googleAuthR.scopes.selected = c('scope1', 'scope2')) before loading library and include one required scope.
Successfully authenticated via /Users/mark/auth.json
Set default bucket name to 'bucket-name'
> employee <- c('John Doe','Peter Gynn','Jolie Hope')
> salary <- c(21000, 23400, 26800)
> startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
> 
> employ.data <- data.frame(employee, salary, startdate)
> gcs_upload(employ.data)
==Google Cloud Storage Object==
Name:            employ.data.csv 
Type:            text/csv 
Size:            135 bytes 
...etc..
```

Otherwise you can pass a string of the bucket name, or a bucket object.  Perhaps confusingly, the list you get from `gcs_list_buckets` are not of bucket objects, I could look at that. You can instead pass `gcs_get_bucket(buckets$name[[1]])` which will pass the character name from the data.frame.


```r
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.3 (unknown)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] googleCloudStorageR_0.2.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9            crayon_1.3.2           digest_0.6.11          withr_1.0.2           
 [5] mime_0.5               R6_2.2.0               jsonlite_1.2           xtable_1.8-2          
 [9] magrittr_1.5           httr_1.2.1.9000        curl_2.3               testthat_1.0.2        
[13] googleAuthR_0.4.0.9000 devtools_1.12.0.9000   tools_3.3.0            shiny_1.0.0           
[17] httpuv_1.3.3           pkgload_0.0.0.9000     pkgbuild_0.0.0.9000    memoise_1.0.0         
[21] htmltools_0.3.5        openssl_0.9.5         
> 
```

**Comment by MarkEdmondson1234** [comment]
Your previous code was passing a character vector of all your bucket names, which passed a check which it shouldn't have, so I've added another check that should fail with a more informative error.

**Comment by MarkEdmondson1234** [comment]
Incidentally, if you are using this from Google Compute Engine, check out the authentication function in the latest version of `googleAuthR` that reuses the GCE auth, meaning you don't need to re-authenticate when on the GCE machine:

```r
?gar_gce_auth()
```

**Comment by prcbnt** [comment]
Thanks a lot for the quick answer. That's amazing !

Indeed the issue lies  with the bucket name. It works when I hardcode the name of the bucket, but not when I use `gcs_get_bucket(buckets$name[[1]])`... I'll have to dig deeper into that, because `buckets$name[[1]]` returns a string with the name of the bucket also.

While testing I ran into another issue (I must say that I am an amateur coder and just starting with R). I have a list of dataframes and I would like to `gcs_upload` each dataframe of the list into a separate CSV on the Cloud Storage.
I tried a simple loop as follows
```
for(i in 1:length(df_list)){
  gcs_upload(df_list[[i]], bucket = bucket)
}
```
but it only uploads the first dataframe of the list. Would you be kind enough to provide a workaround ?

Again thank you very much !

**Comment by MarkEdmondson1234** [comment]
I would do it like this:

```r
## set the bucket name via the global var:
gcs_global_bucket("my-bucket-name")

## use lapply to loop through the list of dataframes
result <- lapply(dataframe_list, gcs_upload)

## inspect result to see if all worked ok
result
```

**Comment by prcbnt** [comment]
Thanks, lapply works fine ; however there is an issue with the name. Dataframes are all uploaded as X[[i]].csv. How can I set the names of each uploaded file to be the name of the dataframe of the list ? And how can I pass arguments to `gcs_upload` in the `lapply` ?

I apologize if my question is more related to my lack of R knowledge than to the package itself, but your help makes me save a LOT of time and pain :)

**Comment by MarkEdmondson1234** [comment]
No worries, if you are a newbie you may want to check out http://www.dartistics.com/ which also points to lots of other resources.

If you want to also specify the name you can pass it in to an individual function like so:

```r
gcs_upload(file, name = "my_name")
```

But for using in `lapply` you don't want it to be the same for each file so need to specify in the upload function.   In that case you need to make your own little function to put in the `lapply` that will be run, which is a little less neat than when you have only one argument like my example in the previous answer.

In that case, I like to name the list I pass in, and use those names as the names of the files.  So first step is to name the list what you want it to be 

```r
### here I set manually via a vector, but perhaps other ways.
names(dataframe_list) <- c("filename1", "fileblah2", "fileblah3', ..etc..)
```

Then we make a function for each element of the list:

```r
### x will be the [[x]] element of the list its looping over
upload_me <- function(x){
  obj <- obj[[x]]
  gcs_upload(obj, name = x)
}
```

Then I pass the names of the list into the loop, which the function uses to get the object (this is a little R trick, represented via the `  obj <- obj[[x]]` line in the function above)

```r
lapply(names(dataframe_list), upload_me)
```

You can also pass fixed elements to an lappy, but they are constant for all loops, so this works (but not neccessary if you use `gcs_global_bucket`)

```r
## the parameter bucket is the same for all calls to function upload_me
lapply(names(dataframe_list, upload_me, bucket = "my_bucket")
```

**Comment by prcbnt** [comment]
Thanks a lot (again), you've been really helpful and an incredible help. 

I had to wrap my mind around your solution, and tweak it just a little to make it work (to remove the row names), like this 
```
upload_me <- function(x){
  f <- function(input, output) write.csv(input, row.names = FALSE, file = output)
  obj <- dataframe_list[[x]]
  gcs_upload(obj, name = x, object_function = f, type = "text/csv", predefinedAcl = "projectPrivate")
}

lapply(names(dataframe_list), upload_me)
```

I changed "obj" by dataframe_list because otherwise it wouldn't work as `Error in FUN(X[[i]], ...) : object 'obj' not found`

**But now weirdly they're not uploaded as CSVs any more and not recognized as such on my local machine ?**

**Comment by MarkEdmondson1234** [comment]
Ah yes, I corrected that error in my comment above. (obj should have been dataframe_list)

I think you have taken the right approach for modifying the csv upload (I would just move the function definition outside of the loop as its only needed once) - when you say they are not CSV is it maybe they are uploaded as CSVs but the name is not including ".csv" at the end?  You could ensure that by doing `paste0(x, ".csv")`.  

Perhaps print a little message to keep track:

```r
f <- function(input, output) write.csv(input, row.names = FALSE, file = output)

upload_me <- function(x){
  obj <- dataframe_list[[x]]
  x <- paste0(x, ".csv")
  message("Uploading: ", x)
  gcs_upload(obj, name = x, object_function = f, type = "text/csv", predefinedAcl = "projectPrivate")
}

lapply(names(dataframe_list), upload_me)
```

**Comment by prcbnt** [comment]
Thanks a lot, Mark. Works like a charm.
I might have future questions as I dig deeper into the package functions ; in the meantime, enjoy your week-end !
