### ISSUE TITLE
Could `gcs_get_object` support decompressing objects?

### ISSUE THREAD

**Issue by nkeriks** [cloudyr/googleCloudStorageR#63]
I haven't poked into how things work behind the scenes, but I do have a directory of `.json.gz` files in GCS and was hoping that they would get parsed correctly by `gcs_get_object`. However, they come through as binary objects, so I have to either write to disk + reread or to uncompress them in GCS. Trying to set global `httr` options hasn't worked for me.

**Comment by MarkEdmondson1234** [comment]
I guess it could, by letting you supply your own parsing function.  This is available for uploads, but no reason why it can't be available for downloads too!

**Comment by MarkEdmondson1234** [comment]
@nkeriks Yep that was no problem to add, thanks!  In Github version now.
