### ISSUE TITLE
Problems downloading 2GB text file

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/googleCloudStorageR#69]
Thread from https://github.com/cloudyr/cloudyr.github.io/issues/15

@fncalderong  said:

Hi, I am using googleCloudStorageRs package. I am trying to download a 2gb txt file with R but have no susses.

I tried to download the file with gcs_get_object function, but the file is in Raw format and is quite dificult to convert it.

I tried to get the URL of the file with gcs_download_url function, but when I try to download the file via URL using downloadFile from R.utils Package it download a html file (the page where google ask the credentials).

@MarkEdmondson1234 said:

Yes best report there, but it sounds like you only need to specify the .txt file extension in the name you have downloaded it to. Try renaming the file.

@fncalderong  said:

when I try to run this:

`gcs_get_object(objects$name[[36]], saveToDisk = "data.txt",bucket)`

I get this:

```
Error in writeBin(bin, saveToDisk) :
  long vectors not supported yet: connections.c:4123
```

where
` objects$name[[36]][1] "20170523/planofull_170523.txt"`
thanks

**Comment by MarkEdmondson1234** [comment]
Hmm ok, this is the save function in base R failing as 2GB is too big.  Will investigate to see if it can be solved.

**Comment by MarkEdmondson1234** [comment]
From ?writeBin: `Only 2^31 - 1 bytes can be written in a single call (and that is the maximum capacity of a raw vector on 32-bit platforms).` 

@leeper is there a work around for this?

**Comment by MarkEdmondson1234** [comment]
Same issue here https://github.com/richfitz/remake/issues/76

**Comment by fncalderong** [comment]
Nice!!!!....thank you so much. the reason I think is beacause gcs_get_object download it in raw format (long vector) and as you said is to big for R. But for instance if I try to download the file using Rcurl with this command: 

URL <- gcs_download_url(objects$name[[36]],bucket,public=T)
library(RCurl)
getURL(URL)
download.file(URL, destfile = "data2.txt", method="wget")

I can download the file successfuly only if I set the file public (I can´t make this for security reasons).

**Comment by MarkEdmondson1234** [comment]
Hmm ok, in that case try  downloading it via the `gcs_download_url` method, as you can set URLs that are not public but accessible via your Google account sign in.

**Comment by fncalderong** [comment]
So, in that way I must always give my credentials by web. Am I rigth?.

**Comment by fncalderong** [comment]
I meant, if i do it with a not public object, the result is a html file (a google page asking credentials).

**Comment by MarkEdmondson1234** [comment]
Yes, as we unfortunately don't have this feature yet, where you could have a signed URL that you can reach via code https://github.com/cloudyr/googleCloudStorageR/issues/54

I'll see if you can use the same auth you have from the other API calls to apply to the download that you can make via `httr::GET`

**Comment by MarkEdmondson1234** [comment]
A horrible hack may be to use [rvest](https://blog.rstudio.org/2014/11/24/rvest-easy-web-scraping-with-r/) to fill in your auth details.

**Comment by MarkEdmondson1234** [comment]
Probably best solution at the moment would be to use the python gsutil tool (https://cloud.google.com/storage/docs/access-control/create-signed-urls-gsutil) , either directly or to create the signed URL, then call that from R.  If necessary you can wrap the python tool in R wrappers if you must stick within R.

**Comment by MarkEdmondson1234** [comment]
Ok it looks like a solved issue in `httr`, so I'll look to implement it https://github.com/hadley/httr/issues/44

**Comment by fncalderong** [comment]
Man that would be awesome!!! I appreciate your help.

**Comment by MarkEdmondson1234** [comment]
Give that a go now from the latest version on github, its working in my local tests for small files at least.

**Comment by MarkEdmondson1234** [comment]
`
gcs_get_object(obj$name[[3]], bucket = "your-project", saveToDisk = "blah.txt", overwrite = TRUE)`

**Comment by fncalderong** [comment]
I will prove this!!!.

**Comment by fncalderong** [comment]
Worked like a charm!!!. you are the best man. thank you so much.

**Comment by MarkEdmondson1234** [comment]
Thanks for bringing it up, now others will benefit too :)
