### ISSUE TITLE
gcs_auth() cannot authenticate

### ISSUE THREAD

**Issue by jgooly** [cloudyr/googleCloudStorageR#81]
I am trying to do a basic authentication with gcs_auth() and receive the following error.

R code:
```
library(googleCloudStorageR)
gcs_auth()
```
error:
```
Error in gar_auto_auth(required_scopes, new_user = new_user, no_auto = no_auto,  : 
Cannot authenticate - options(googleAuthR.scopes.selected) needs to be set to include 
https://www.googleapis.com/auth/devstorage.full_control or 
https://www.googleapis.com/auth/devstorage.read_write or 
https://www.googleapis.com/auth/cloud-platform
```

I see the reference to the scopes listed in the error message when calling:
```
> gcs_auth
function (new_user = FALSE, no_auto = FALSE) 
{
    required_scopes <- c("https://www.googleapis.com/auth/devstorage.full_control", 
        "https://www.googleapis.com/auth/devstorage.read_write", 
        "https://www.googleapis.com/auth/cloud-platform")
    gar_auto_auth(required_scopes, new_user = new_user, no_auto = no_auto, 
        environment_var = "GCS_AUTH_FILE")
}
<environment: namespace:googleCloudStorageR>
```
Hopefully, I am doing/missing something trivial but I'm hitting a wall now.
Many thanks in advance!

R version 3.3.2
googleCloudStorageR_0.4.0

**Comment by MarkEdmondson1234** [comment]
Sorry for the trouble - the best way to authenticate is to use the service JSON file which will take care of this for you, see http://code.markedmondson.me/googleCloudStorageR/articles/googleCloudStorageR.html

Short-term you can also auth using `gcs_auth()` by setting the scopes first via

```r
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
library(googleCloudStorageR)
gcs_auth()
```

Its a bug that this isn't set for you, so I'll fix that.

**Comment by jgooly** [comment]
Thanks Mark. I did try setting the options and now receive the following error.

code:

```
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/cloud-platform")
library(googleCloudStorageR)
gcs_auth()
```

error:

```
Error: option('googleAuthR.client_id') has not been set
```

**Comment by MarkEdmondson1234** [comment]
If you can I heavily recommend using the auto-auth method on the website, that will sort it out.

Otherwise I just pushed a change to GitHub - use that then download the clientID JSON as detailed in the help of `?googleAuthR::gar_set_client()` 

```r
googleAuthR::gar_set_client("location-of-clientjson.json")
library(googleCloudStorageR)
gcs_auth()
```

**Comment by jgooly** [comment]
Thanks Mark! Will give it a shot.

**Comment by jgooly** [comment]
Also, to be clear, 

> I heavily recommend using the auto-auth method on the website

You are referring to `gar_auto_auth("https://www.googleapis.com/auth/cloud-platform", new_user = TRUE)` correct?

**Comment by MarkEdmondson1234** [comment]
Not that, I mean downloading a JSON auth file (not the JSON client id from above), saving to your computer, then setting up a environment argument GCS_AUTH_FILE that points to that file:

http://code.markedmondson.me/googleCloudStorageR/articles/googleCloudStorageR.html#auto-authentication

Authentication requires you to set environment arguments with your setup details.

These can be set in an .Renviron file located on your computer home directory - R will look in this file upon startup. Read more via ?Startup

The easiest way to find the right home directory is within RStudio, to click on the Home button in RStudio’s file explorer. Create a file via File > New file > Text File, save and call it .Renviron

My .Renviron file looks a bit like this:

```
GCS_AUTH_FILE="/Users/mark/xxxxx/auth.json"
```

The GCE_AUTH_FILE points to the file location of the service account JSON file taken from your Google Project. The other arguments set the default project and zone.

This file will then used for authentication when you load the library

**Comment by MarkEdmondson1234** [comment]
I have added a default Google project again to help with this issue, although I still recommend using the auto-auth method with your own JSON detailed above.

**Comment by djsd123** [comment]
The JSON auth file solution would not scale very well for my use case.  We have lots of notebook users on GCP and preferred that notebook instances be ephemeral.  Worked around like so using [gargle](https://gargle.r-lib.org/):

```
library(googleCloudStorageR)
library(gargle)

scope <-c('https://www.googleapis.com/auth/cloud-platform')
token <- token_fetch(scopes = scope)

gcs_auth(token = token)

gcs_list_objects(bucket = 'my-bucket')
```

**Comment by MarkEdmondson1234** [comment]
This is possible now as `gargle` uses the default GCE authentication when on GCP resources.  The `googleAuthR::gar_gce_auth()` should also do it as its calling the same functions underneath.
