### ISSUE TITLE
Weird error with googleCloudStorage and opencpu

### ISSUE THREAD

**Issue by riccardopinosio** [cloudyr/googleCloudStorageR#90]
Hello,

I am encountering a weird behaviour of the package when used with opencpu. In particular, I have a function that fetches an object from a bucket when passed the object name:

```r
get_gcs_data <- function(target_object_id){

connect_gcs()
object <- googleCloudStorageR::gcs_get_object(target_object_id, parseObject = FALSE)
    object_data <- httr::content(object, type = 'text/csv')
    return(object_data)
}
```

Now the spooky thing is this: when called from Rstudio the function does what it's supposed to do (return the data); when called from opencpu most of the time the function returns the data, but sometimes opencpu returns the following error:

```
HTTP 400 bad request.

File not found. Check object_name and if you have read permissions.
Looked for [filename]

In call:
googleCloudStorageR::gcs_get_object(target_object_id, parseObject = FALSE)
```

Now the object certainly exists, and the error seems kind of random; sometimes the call goes through, sometimes it fails. Any ideas on where the catch could be?

**Comment by riccardopinosio** [comment]
Ok, I think I have isolated the problem:

Since the function worked well on rstudio server but not on opencpu, I suspected the opencpu R processes were not loading the environment variables which store the secrets to open a connection to google cloud storage, and indeed that was the problem: the connect_gcs() function called in the function above actually looks like:

`connect_gcs <- function(){
  googleAuthR::gar_auth_service(json_file = Sys.getenv('BQ_AUTH_FILE'),
                                scope = 'https://www.googleapis.com/auth/cloud-platform')
  googleCloudStorageR::gcs_global_bucket(Sys.getenv('GCS_MAIN_BUCKET'))
}
`

It turns out the 'GCS_MAIN_BUCKET' environment variable was not set for the opencpu processes and therefore returned the empty string "".
However this raises the question: why does the call to gcs_get_object sometime work and sometimes not work when the global bucket is the empty string ""? Would it not be better to throw an error immediately?

**Comment by riccardopinosio** [comment]
Further updates [here:](https://groups.google.com/forum/#!topic/opencpu/CMWhdGZFu0c)

**Comment by MarkEdmondson1234** [comment]
Hello, the `gcs_global_bucket` is convenient as it means you don't need to pass the bucket name each time, but it sounds like sometimes the R environment is not the same for each OpenCPU (which makes sense, I guess it forks R sessions when experiencing higher loads).  

In that case, I suggest passing in the bucket name directly to the function, all the `gcs_` functions should have it, e.g.

```r
googleCloudStorageR::gcs_get_object(target_object_id, parseObject = FALSE, bucket = "my-bucket-name")
```

Incidentally I don't see why you have `parseObject = FALSE` then do what the parsing does anyhow ;)  If you do want to customise that though, you can pass it into the function via `parseFunction` function.

**Comment by MarkEdmondson1234** [comment]
> why does the call to gcs_get_object sometime work and sometimes not work when the global bucket is the empty string ""?

I thought it should throw an error, I will check that

**Comment by MarkEdmondson1234** [comment]
The code here https://github.com/cloudyr/googleCloudStorageR/blob/master/R/buckets.R#L15 checks if the bucket is a string, but not an empty string, so I will fix that.
