### ISSUE TITLE
"Configuring your own Google Project" Instructions Confusion

### ISSUE THREAD

**Issue by ben519** [cloudyr/googleCloudStorageR#94]
Trying out this package for the first time.  I'm having trouble following the setup instructions for [Configuring your own Google Project](https://github.com/cloudyr/googleCloudStorageR#configuring-your-own-google-project).

Per the guide,

> The instructions below are for when you visit the Google API console (https://console.developers.google.com/apis/)

Let's pull up that link in my console.. It looks like this

<img width="1647" alt="screen shot 2018-09-05 at 2 40 58 pm" src="https://user-images.githubusercontent.com/723099/45117061-3ae2ac80-b11a-11e8-97ed-6eb88327c613.png">

> 1. Click 'Create a new Client ID', and choose "Installed Application".

Hmm, I don't see any option to "Create a new Client ID". Maybe this is now under Credentials > Create Credentials?

<img width="773" alt="screen shot 2018-09-05 at 2 45 49 pm" src="https://user-images.githubusercontent.com/723099/45117141-6f566880-b11a-11e8-8428-d42335668d74.png">

> 2. Download the client ID JSON.

<img width="425" alt="screen shot 2018-09-05 at 2 48 11 pm" src="https://user-images.githubusercontent.com/723099/45117279-c3f9e380-b11a-11e8-8483-9c27523634b3.png">

If I click Create Credentials, I *think* I'm supposed to choose "Service Account Key"? However, in doing this I end up with a JSON file such that, when I call `googleAuthR::gar_set_client("config/my-credentials.json")` I get the error 

```
Error in googleAuthR::gar_set_client("config/ticketarb-storage-account-credentials2.json") : 
  $installed not found in JSON - have you downloaded the correct JSON file? 
           (Service account client > Other, not Service Account Keys)
```

What am I missing here?

Thanks!

**Comment by MarkEdmondson1234** [comment]
Its two JSON files - one for authentication that you use for auto-authentication, another sets the client ID that dictates which Cloud project you are authenticating through - often the same project.  

To help explain authentication with another library (googleLanguageR) this video shows the same process and explains a bit about what each are (from 21mins onwards)  https://youtu.be/4Ht_vEXJ4wo?t=21m1s

**Comment by ben519** [comment]
Thanks for the help Mark - I was able to get things working, it seems.  Outlining my steps below for future reference and others who may find this.

The key thing to understand is that *everything* in Google Cloud Console should be done within the APIs & Services section, whose homepage looks like this

![screen shot 2018-09-06 at 10 57 28 am](https://user-images.githubusercontent.com/723099/45169671-ba788600-b1c3-11e8-8f2c-3cfd88f9ec29.png)

1. Enable Google Cloud Storage API
2. Credentials >> Create Credentials >> OAuth Client ID >> Other

<img width="687" alt="screen shot 2018-09-06 at 10 59 15 am" src="https://user-images.githubusercontent.com/723099/45169827-06c3c600-b1c4-11e8-8bc0-d3915d55eadc.png">
<img width="266" alt="screen shot 2018-09-06 at 10 59 35 am" src="https://user-images.githubusercontent.com/723099/45169835-07f4f300-b1c4-11e8-9fbf-15ba52cd3164.png">

Save the JSON file as something like *my-ClientID-credentials.json*

3. Credentials >> Create Credentials >> Service Account Key

Save the JSON file as something like *my-service-account-credentials.json*

4. Code to get up and running

```
# Google cloud storage

# Setup
library(googleCloudStorageR)
options(googleAuthR.scopes.selected = "https://www.googleapis.com/auth/devstorage.full_control")

# Authenticate ClientID
googleAuthR::gar_set_client("path/to/my-ClientID-credentials.json")

# Authenticate service account
Sys.setenv("GCS_AUTH_FILE" = "full/path/to/my-service-account-credentials.json")
googleCloudStorageR::gcs_auth()

## Get bucket info
gcs_list_buckets(projectId = "my-project")
```

**Comment by gavin-zenfolio** [comment]
In case anyone else lands here, it looks like the option for 'other' in the application type is gone. I went with new option 'desktop app' and it worked fine with that.
