### ISSUE TITLE
gcs_list_objects limits number of objects

### ISSUE THREAD

**Issue by himanshu-sikaria** [cloudyr/googleCloudStorageR#97]
`gcs_list_objects` outputs a maximum of 1000 objects, can this be a function input?

**Comment by MarkEdmondson1234** [comment]
Which version are you using? The latest version should return all objects.

**Comment by MarkEdmondson1234** [comment]
Yes was fixed a year ago https://github.com/cloudyr/googleCloudStorageR/issues/58

**Comment by himanshu-sikaria** [comment]
Was using the CRAN verison. Sorry, should have checked the issues before opening another. Thanks. Would be great if you could update the CRAN version.

**Comment by MarkEdmondson1234** [comment]
That’s the confusing thing, the fix should be on CRAN :)
